version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - erunion
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - erunion
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    ignore:
      # The following are packages that we're ignoring updates from because they've moved to being
      # ESM-only packages and we can't yet upgrade them.
      - dependency-name: chalk
        versions:
          - ">= 5"
      - dependency-name: execa
        versions:
          - ">= 6"
      - dependency-name: figures
        versions:
          - ">= 4"
      - dependency-name: form-data-encoder
        versions:
          - ">= 2"
      - dependency-name: ora
        versions:
          - ">= 6"
      - dependency-name: stringify-object
        versions:
          - ">= 4"
